name: Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.2.6 # This is the action
        with:
          heroku_api_key: 6eb8dd7a-5400-4d53-ad1a-9eb5fffaaaa7
          heroku_app_name: "danielecarta-docs" #Must be unique in Heroku
          heroku_email: "crtdaniele@gmail.com"
          procfile: "web: cd website"  
